### ISSUE TITLE
Deprecation issue with 2.18.0

### ISSUE THREAD

**Issue by bungeye** [miguelcobain/ember-paper-expansion-panels#3]
installed dependencies ember-cli-babel@5.2.4 and ember-cli-htmlbars@1.3.4 using ember-cli-version-checker@1.3.1 which causes deprecation as per: 

[https://github.com/ember-cli/ember-cli-version-checker/issues/48#issuecomment-354912902](https://github.com/ember-cli/ember-cli-version-checker/issues/48#issuecomment-354912902)

**Comment by miguelcobain** [comment]
This should be fixed in version 0.0.2.

**Comment by bungeye** [comment]
thanks!
